spring:
  application:
    name: BeekeepingApi
  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:beekeping_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:beekeping_db}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  datasource:
    driver-class-name: org.postgresql.Driver